name: domain
description: root domain resolutions

steps:
  - scripts:
      - cat $projectName$-cero.txt | unfurl format %r.%t | sort -u > $projectName$-root-domain.txt
  - postRun:
      - $projectName$-root-domain.txt