name: ip
description: ip resolotion

steps:
  - scripts:
      - cat $projectName$-final.txt $projectName$-lives.txt | sed 's+http[s]*://++g' | sort -u | dnsx -re > $projectName$-sub-ip.txt
  - postRun:
      - $projectName$-sub-ip.txt