name: subdomain
description: Subdomain enumeration passive and active

steps:
  - scripts:
      - subfinder -d $domain$ -all -o $projectName$-subfinder.txt -silent -config $configPath$/subfinder.yaml
      - amass enum -passive -d $domain$ -config $configPath$/amass.ini -o $projectName$-amass.txt -silent
      - findomain -t $domain$ | tee $projectName$-findomain.txt
      - chaos -d $domain$ -key $chaosApi$ -o $projectName$-chaos.txt
      - SELECT
        ci.NAME_VALUE
        FROM
        certificate_and_identities ci
        WHERE
        plainto_tsquery('certwatch', '$domain$') @@ identities(ci.CERTIFICATE)
        END
        )
        echo "$query" | psql -t -h crt.sh -p 5432 -U guest certwatch | sed 's/ //g' | grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox} -E --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox} ".*.\.$1" | sed 's/*\.//g' | tr '[:upper:]' '[:lower:]' | sort -u | tee $projectName$-crt.txt
      - curl -s 'https://seckrd.com/subdomain-finder' --header 'user-agent: Mozilla/5.0 (Macintosh Intel Mac OS X 10_15_7) AppleWebKit/537.36 (, like Gecko)/114.0.00 Safari/537.36' --data-urlencode "domain=$domain$" --data-url 'submit=' | grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox} -oE "https?://[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}" | sed -E "s/^https?:\/\///" | tee  $projectName$-secrd.txt
      - curl -s https://rapiddns.io/subdomain/$domain$\?full\=1 | grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox} -oE "[a-zA-Z0-9._-]+\.$domain$" | tee  $projectName$-rapidns.txt
      - assetfinder -subs-only $domain$ > $projectName$-assetFinder.txt
      - cat $projectName$-* | sort -u > $projectName$-passive.txt
  - switches:
      - WC: shuffledns -l $projectName$-passive.txt -o $projectName$-resolves.txt
      - NWC: dnsx -l $projectName$-passive.txt -o $projectName$-resolves.txt
  - scripts:
      - puredns bruteforce $wordlist$/wordlist.txt $domain$ --resolvers $resolver$/resolver.txt > $projectName$-puredns.txt
      - cat $projectName$-puredns.txt $projectName$-resolves.txt | sort -u > $projectName$-full-resolves.txt
  - switches:
      - PR: cat $projectName$-full-resolves.txt | dnsgen - | dnsx -re -silent | sort -u > $projectName$-final.txt
      - PP: cat $projectName$-puredns.txt $projectName$-passive.txt | dnsgen - | dnsx -re -silent | sort -u > $projectName$-final.txt
      - PN: cat $projectName$-full-resolves.txt | dnsx -re | sort -u > $projectName$-final.txt
  - scripts:
      - cat $projectName$-final | awk '{print $1}' | sort -u > $projectName$-finalLive.txt
      - cat $projectName$-finalLive.txt | httpx -silent -follow-host-redirects -title -status-code -cdn -tech-detect | sort -u > $projectName$-lives.txt
  - postRun:
      - $projectName$-passive.txt
      - $projectName$-final.txt
      - $projectName$-lives.txt



